name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.GHA_DEPLOY_SSH_PRIVATE_KEY }}

    - name: Disable Host key verification
      run: |
        mkdir -p ~/.ssh
        echo "StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Deploy
      run: docker-compose up -d
      env:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_HOST: ssh://gha@20.199.89.238

